repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Ensures that a file is either empty, or ends with one newline.
      - id: end-of-file-fixer
      # Trims trailing whitespace.
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      # Code formatting for Python
      - id: black-jupyter
        args: [--config=pyproject.toml]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Linting for Python
      - id: ruff
        args: [--config=pyproject.toml]
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      # Linting for reStructuredText
      - id: doc8
        args: [--config=pyproject.toml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      # Linting for YAML
      - id: yamllint
        args: [--strict, --config-file=.yamllint.yaml]
