# Builds the Sphinx documentation & push it to GitHub Pages
name: Docs Build & Push

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - cneuromax/**
      - .github/workflows/docs-build-push.yaml

jobs:
  docs-build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Build the documentation
        id: build-docs
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          pyproject_extras: null
          sphinx_version: null
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.build-docs.outputs.artifact }}
