# Builds the Sphinx documentation
name: Docs Build

on:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - cneuroml/**
      - pyreqs/documentation.txt
      - .github/workflows/docs-build.yaml

jobs:
  docs-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build the documentation
        uses: sphinx-notes/pages@v3
        with:
          publish: false
          pyproject_extras: null
          requirements_path: ./pyreqs/documentation.txt
          sphinx_version: null
