# Runs pytest & mypy (type checking and unit tests)
name: Typecheck & Unittest

on:
  pull_request:
    branches: [main]
    paths:
      - cneuromax/**
      - pyproject.toml
      - .github/workflows/typecheck-unittest.yaml
  push:
    branches: [main]
    paths:
      - cneuromax/**
      - pyproject.toml
      - .github/workflows/typecheck-unittest.yaml

permissions:
  contents: read

jobs:
  typecheck-unittest:
    runs-on: self-hosted
    steps:
      - name: Install OpenMPI
        run: sudo apt install -y libopenmpi-dev
      - name: Checkout the GitHub repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create virtual environment
        run: python3 -m venv venv
      - name: Activate virtual environment
        run: . venv/bin/activate
      - name: Install dependencies
        run: >
          pip install --no-cache-dir --upgrade pip && pip install
          --extra-index-url https://download.pytorch.org/whl/cpu -e .[dev]
      - name: Run mypy
        run: mypy --config-file=pyproject.toml cneuromax
      - name: Run pytest
        run: pytest --cov cneuromax
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
